const mockContentData = {
  topViewed: [
    { title: "Article A", views: 120 },
    { title: "Article B", views: 110 },
    { title: "Article C", views: 95 },
    { title: "Article D", views: 80 },
    { title: "Article E", views: 75 },
    { title: "Article F", views: 60 },
    { title: "Article G", views: 55 },
    { title: "Article H", views: 50 },
    { title: "Article I", views: 45 },
    { title: "Article J", views: 40 },
  ],
  topSaved: [
    { title: "Article A", saves: 80 },
    { title: "Article B", saves: 75 },
    { title: "Article C", saves: 60 },
    { title: "Article D", saves: 55 },
    { title: "Article E", saves: 50 },
    { title: "Article F", saves: 45 },
    { title: "Article G", saves: 40 },
    { title: "Article H", saves: 35 },
    { title: "Article I", saves: 30 },
    { title: "Article J", saves: 25 },
  ],
  thumbsUp: [
    { title: "Article A", upvotes: 50 },
    { title: "Article B", upvotes: 45 },
    { title: "Article C", upvotes: 40 },
    { title: "Article D", upvotes: 38 },
    { title: "Article E", upvotes: 35 },
    { title: "Article F", upvotes: 30 },
    { title: "Article G", upvotes: 28 },
    { title: "Article H", upvotes: 25 },
    { title: "Article I", upvotes: 20 },
    { title: "Article J", upvotes: 15 },
  ],
  thumbsDown: [
    { title: "Article P", downvotes: 5 },
    { title: "Article Q", downvotes: 7 },
    { title: "Article R", downvotes: 8 },
    { title: "Article T", downvotes: 10 },
    { title: "Article U", downvotes: 12 },
    { title: "Article K", downvotes: 15 },
    { title: "Article L", downvotes: 18 },
    { title: "Article M", downvotes: 20 },
    { title: "Article O", downvotes: 25 },
    { title: "Article I", downvotes: 30 },
  ],
  topSearchTerms: [
    { term: "Diabetes", count: 30 },
    { term: "Hypertension", count: 28 },
    { term: "Asthma", count: 25 },
    { term: "Back Pain", count: 20 },
    { term: "Migraine", count: 18 },
    { term: "Depression", count: 15 },
    { term: "Insomnia", count: 12 },
    { term: "Obesity", count: 10 },
    { term: "Arthritis", count: 8 },
    { term: "Allergy", count: 5 },
  ],
  zeroResultSearch: [
    { term: "Rare Disease X", count: 5 },
    { term: "Condition Y", count: 4 },
    { term: "Symptom Z", count: 3 },
    { term: "Uncommon Test", count: 3 },
    { term: "Unknown Treatment", count: 2 },
    { term: "Rare Surgery", count: 2 },
    { term: "Special Therapy", count: 1 },
    { term: "New Drug", count: 1 },
    { term: "Experimental Procedure", count: 1 },
    { term: "Unknown Procedure", count: 1 },
  ],
  mostFrequentlySavedQuestions: [
    { term: "Could this pain be a sign of something serious like an infection, bleeding, or blockage?", count: 30 },
    { term: "Based on my symptoms, do I need an urgent imaging study?", count: 28 },
    { term: "Given that I have back pain and abdominal pain, do I need imaging to rule out something serious like an aneurysm?", count: 25 },
    { term: "If there is possible bleeding in my digestive tract, do I need an urgent scan now before seeing a gastroenterologist for an endoscopy?", count: 20 },
    { term: "Even if my lab tests are normal, should I also get an ultrasound to make sure we are not missing anything?", count: 18 },
    { term: "If my ultrasound is normal but the pain continues, should I get additional imaging?", count: 15 },
    { term: "Given my positive pregnancy test result, should I get an ultrasound to rule out an ectopic pregnancy?", count: 12 },
    { term: "Given my weakened immune system, would I benefit from a CT scan to make sure we are not missing anything?", count: 10 },
    { term: "Since I’m over 65, would a CT scan be recommended to help rule out serious causes?", count: 8 },
    { term: "What warning signs mean I need to go to the emergency room immediately?", count: 5 },
  ],
};

export default mockContentData;
